version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST}
      KAFKA_CREATE_TOPICS: "retail-product:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  producer:
    build:
      context: ./retail-streamer
      dockerfile: Dockerfile
    image: retail-streamer-fastapi:latest
    # depends_on:
    #   - kafka
    #   - zookeeper
    restart: unless-stopped
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./retail-streamer/producer/:/usr/src/app
    ports:
      - 8002:8000
    environment:
      KAFKA_INSTANCE: localhost:9092

  consumer:
    image: retail-streamer-fastapi:latest
    # depends_on:
    #   - kafka
    #   - zookeeper
    restart: unless-stopped
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - ./retail-streamer/consumer/:/usr/src/app
    ports:
      - 8003:8001
    environment:
      KAFKA_INSTANCE: localhost:9092

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
